version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: spring_blog_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: spring_blog_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    container_name: spring_blog_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  api:
    build: .
    container_name: spring_blog_api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - mailhog
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring_blog_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME:mailuser
      - SPRING_MAIL_PASSWORD:mailpass

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
    driver: local